dependencies:
  - name: postgresql
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
