apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" .}}-config
data:
{{ toYaml .Values.cabot | indent 2 }}
{{- if not .Values.cabot.DJANGO_SECRET_KEY -}}
  DJANGO_SECRET_KEY: {{ randAlphaNum 32 }}
{{- end -}}
